-- begin FOOTBALLGAME_TEAM
create unique index IDX_FOOTBALLGAME_TEAM_UNIQ_NAME on FOOTBALLGAME_TEAM (NAME)^
-- end FOOTBALLGAME_TEAM
-- begin FOOTBALLGAME_LOG_TABLE
alter table FOOTBALLGAME_LOG_TABLE add constraint FK_FOOTBALLGAME_LOG_TABLE_ON_TEAM_NAME foreign key (TEAM_NAME_ID) references FOOTBALLGAME_TEAM(ID)^
create index IDX_FOOTBALLGAME_LOG_TABLE_ON_TEAM_NAME on FOOTBALLGAME_LOG_TABLE (TEAM_NAME_ID)^
-- end FOOTBALLGAME_LOG_TABLE
-- begin FOOTBALLGAME_FIXTURE
alter table FOOTBALLGAME_FIXTURE add constraint FK_FOOTBALLGAME_FIXTURE_ON_TEAM1 foreign key (TEAM1_ID) references FOOTBALLGAME_TEAM(ID)^
alter table FOOTBALLGAME_FIXTURE add constraint FK_FOOTBALLGAME_FIXTURE_ON_TEAM2 foreign key (TEAM2_ID) references FOOTBALLGAME_TEAM(ID)^
create index IDX_FOOTBALLGAME_FIXTURE_ON_TEAM1 on FOOTBALLGAME_FIXTURE (TEAM1_ID)^
create index IDX_FOOTBALLGAME_FIXTURE_ON_TEAM2 on FOOTBALLGAME_FIXTURE (TEAM2_ID)^
-- end FOOTBALLGAME_FIXTURE
