
alter table FOOTBALLGAME_FIXTURE add constraint FK_FOOTBALLGAME_FIXTURE_ON_TEAM1 foreign key (TEAM1_ID) references FOOTBALLGAME_TEAM(ID);
alter table FOOTBALLGAME_FIXTURE add constraint FK_FOOTBALLGAME_FIXTURE_ON_TEAM2 foreign key (TEAM2_ID) references FOOTBALLGAME_TEAM(ID);
create index IDX_FOOTBALLGAME_FIXTURE_ON_TEAM1 on FOOTBALLGAME_FIXTURE (TEAM1_ID);
create index IDX_FOOTBALLGAME_FIXTURE_ON_TEAM2 on FOOTBALLGAME_FIXTURE (TEAM2_ID);
